name: ppp
favicon: null
layout_spectrum: 0.37274474767036736
typography_spectrum: 0.7203549051191658
title: Projects Productivity Passion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05222857207991183
  lightness: 0.6450285641476512
  saturation: 0.7165128835476935
  rhythmicContrast: 0.7979085424449295
purpose: []
